name: 'Sets up project'
description: 'Installs Node.js, pnpm, and project dependencies.'
runs:
  using: "composite"
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@10693b3829bf86eb2572aef5f3571dcf5ca9287d # v2.2.2
      with:
        version: 7.13.1
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: pnpm
    - name: Install dependencies and build
      run: pnpm install --prefer-offline
      shell: bash
